/**
 * Reads standupCatalogSource.txt (pasted catalog: lines "Name — [meta…]") and
 * writes cardsdeven/src/standupComedianPhrases.generated.js for bundling without ?raw.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');
const srcPath = path.join(root, 'standupCatalogSource.txt');
const outPath = path.join(root, 'cardsdeven', 'src', 'standupComedianPhrases.generated.js');

function stripNikkud(s) {
  return s.replace(/[\u0591-\u05C7\u05BF\u05C0\u05C4\u05C5\u05C6]/g, '');
}

function normalizePhrase(s) {
  return stripNikkud(String(s || ''))
    .toLowerCase()
    .replace(/\s+/g, ' ')
    .replace(/["'`׳״]/g, '')
    .trim();
}

function addPhrase(raw, set) {
  const n = normalizePhrase(raw);
  if (!n) return;
  const hasHebrew = /[\u0590-\u05FF]/.test(n);
  if (hasHebrew) {
    if (n.length >= 3) set.add(n);
  } else if (n.length >= 4) {
    set.add(n);
  }
}

function splitSubnames(s) {
  return String(s)
    .split(/\s*\/\s*|\s+-\s+|,\s*/)
    .map((x) => x.trim())
    .filter(Boolean);
}

function parseCatalog(text) {
  const phrases = new Set();
  for (const line of text.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const idx = trimmed.indexOf(' — [');
    if (idx === -1) continue;
    let head = trimmed.slice(0, idx).trim();
    if (/^קטלוג\s/u.test(head)) continue;
    if (/^[א-ת]{1,2}$/u.test(head)) continue;
    if (/^[החט],\s/u.test(head)) continue;
    const chunks = head.split(',').map((c) => c.trim()).filter(Boolean);
    for (let chunk of chunks) {
      chunk = chunk.replace(/^[א-ת]\.\s*/, '').trim();
      const paren = chunk.match(/^(.+?)\s*\(([^)]+)\)\s*$/u);
      if (paren) {
        splitSubnames(paren[1]).forEach((p) => addPhrase(p, phrases));
        splitSubnames(paren[2]).forEach((p) => addPhrase(p, phrases));
      } else {
        splitSubnames(chunk).forEach((p) => addPhrase(p, phrases));
      }
    }
  }
  const sorted = [...phrases].sort((a, b) => b.length - a.length);
  return sorted;
}

const text = fs.readFileSync(srcPath, 'utf8');
const phrases = parseCatalog(text);
const body = `/* eslint-disable */\n/** Auto-generated by scripts/buildStandupPhrases.mjs — do not edit. */\nexport const STANDUP_COMEDIAN_PHRASES_SORTED = ${JSON.stringify(phrases, null, 0)};\n`;
fs.writeFileSync(outPath, body, 'utf8');
console.log('Wrote', outPath, 'phrases:', phrases.length);
